# Generated by Django 5.2 on 2025-11-06 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('retardo', 'Retardo'), ('falta', 'Falta'), ('justificada', 'Falta Justificada')], default='normal', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='control.empleado')),
            ],
            options={
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
