# Generated by Django 5.2 on 2025-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='justificante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='justificantes/'),
        ),
    ]
