# Generated by Django 5.2 on 2025-11-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_asistencia_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre opcional para identificar el horario', max_length=100, null=True)),
                ('dias_laborales', models.CharField(help_text='Días laborales separados por comas (p.ej. Lunes,Martes)', max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='empleados', to='control.horario'),
        ),
    ]
