# Generated by Django 5.2 on 2025-11-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_horario_empleado_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_url', models.URLField(blank=True, help_text='URL opcional del justificante', null=True)),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='justificantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificantes', to='control.asistencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificantes', to='control.empleado')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
