# Generated by Django 5.2 on 2025-11-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_justificante_archivo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
