# Generated by Django 5.2 on 2025-11-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_asistencia_hora_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retardo_minutos', models.PositiveIntegerField(default=5, help_text='Minutos de tolerancia para considerar un retardo')),
            ],
        ),
    ]
