# Generated by Django 5.2 on 2025-11-25 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_systemconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Pase de Entrada'), ('salida', 'Pase de Salida')], max_length=20)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('hora_reincorporacion', models.TimeField(blank=True, help_text='Hora de reincorporación (opcional)', null=True)),
                ('asunto', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='pases/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pases_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='control.empleado')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
