# Generated by Django 5.2 on 2025-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='periodo',
            field=models.CharField(blank=True, help_text='Periodo en formato YYYY-MM para notificaciones periódicas', max_length=7, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together={('empleado', 'periodo', 'titulo')},
        ),
    ]
