# Generated by Django 5.2 on 2025-12-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_notificacion_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('retardo', 'Retardo'), ('falta', 'Falta'), ('justificada', 'Justificada')], default='normal', max_length=20),
        ),
    ]
